### PR TITLE
Handle failures getting terminal size on windows

### LINKED ISSUE #369: Crash on Windows when running on GHA agents
When testing a CLI app  that depends on Swift Argument Parser on GitHub Actions on Windows, it crashes with this stack trace (full CI run logs available [here](https://github.com/MaxDesiatov/Kara/runs/4109994579?check_suite_focus=true), but the link may expire in a few days):

```
Swift/Collection.swift:1308: Fatal error: Can't take a prefix of negative length from a collection
2603
Current stack trace:
2604
0    (null)                             0x00007ff8aa77a550 swift_stdlib_reportFatalErrorInFile + 134
2605
1    (null)                             0x00007ff8aa419d70 _isStdlibInternalChecksEnabled() + 1932
2606
2    (null)                             0x00007ff8aa419d70 _isStdlibInternalChecksEnabled() + 864
2607
3    (null)                             0x00007ff8aa419d70 _isStdlibInternalChecksEnabled() + 179
2608
4    (null)                             0x00007ff8aa419830 _assertionFailure(_:_:file:line:flags:) + 521
2609
5    (null)                             0x00007ff8aa451c20 Collection.prefix(_:) + 1415
2610
6    (null)                             0x00007ff6ac6cab30 String.wrapped(to:wrappingIndent:) + 1070
2611
7    (null)                             0x00007ff6ac6a3180 HelpGenerator.Section.Element.rendered(screenWidth:) + 443
2612
8    (null)                             0x00007ff6ac6a4460 HelpGenerator.Section.rendered(screenWidth:) + 1650
2613
9    (null)                             0x00007ff6ac6b1030 type metadata accessor for HelpGenerator.DiscussionSection + 820
2614
10   (null)                             0x00007ff6ac6a4460 HelpGenerator.Section.rendered(screenWidth:) + 1700
2615
11   (null)                             0x00007ff8aa4058a0 Collection.map<A>(_:) + 597
2616
12   (null)                             0x00007ff6ac6a4460 HelpGenerator.Section.rendered(screenWidth:) + 644
2617
13   (null)                             0x00007ff6ac6abc20 HelpGenerator.rendered(screenWidth:) + 5202
2618
14   (null)                             0x00007ff6ac6b1030 type metadata accessor for HelpGenerator.DiscussionSection + 1615
2617
15   (null)                             0x00007ff6ac6aec20 BidirectionalCollection<>.dumpHelpArgumentDefinition() + 2004
2619
16   (null)                             0x00007ff8aa4058a0 Collection.map<A>(_:) + 597
2620
17   (null)                             0x00007ff6ac6abc20 HelpGenerator.rendered(screenWidth:) + 782
2621
18   (null)                             0x00007ff6ac6b21c0 MessageInfo.init(error:type:) + 10606
2622
19   (null)                             0x00007ff6ac627d70 static ParsableArguments.exit(withError:) + 337
2623
20   (null)                             0x00007ff6ac6394f0 static ParsableCommand.main(_:) + 471
2624
21   (null)                             0x00007ff6ac639720 static ParsableCommand.main() + 72
2625
22   (null)                             0x00007ff6ac8ed060 main + 35
2626
23   (null)                             0x00007ff6ac8ed060 main + 720
2627
24   (null)                             0x00007ff8dc857960 BaseThreadInitThunk + 20
2628
25   (null)                             0x00007ff8df66a2d0 RtlUserThreadStart + 33
```

I'd assume the root cause of this is that screen width is inferred to have some amount of columns less than desired indentation, possibly 0? Thus `HelpGenerator.Section.Element.rendered(screenWidth:)` is called with that invalid screen width passed.

I don't know what the best fix should be. Maybe some default screen width value on Windows for such CI runs? I'm not sure how this is handled on other platforms.

**ArgumentParser version:** `1.0.1` or the `main` branch.
**Swift version:** Reproducible with Swift 5.4 and 5.5

### Checklist
- [x] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce
Make app depending on Swift Argument Parser print help info on GitHub Actions Windows hosts.

### Expected behavior
The app should print help info successfully.

### Actual behavior
The app crashes with the stacktrace shared above.

### PR DESCRIPTION
**Pull request by rauhul**
- Fixes #369
- Adds an error check for the return value of GetConsoleScreenBufferInfo
  Windows. If GetConsoleScreenBufferInfo a default size of 80 by 25 is
  used.

### CODE REVIEW

**Comment by rauhul** [comment]
@compnerd could you take a look at this change, I've never programmed against Windows APIs and I'm not sure how Windows `BOOL`s work in Swift.

**Comment by rauhul** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
> @compnerd could you take a look at this change, I've never programmed against Windows APIs and I'm not sure how Windows `BOOL`s work in Swift.

`BOOL` works similar to `BOOL` in ObjC.  You should treat it as a `Bool`.

File: Sources/ArgumentParser/Usage/HelpGenerator.swift [hunk 1]
```diff
@@ -353,8 +353,10 @@ func _terminalSize() -> (width: Int, height: Int) {
   return (80, 25)
 #elseif os(Windows)
   var csbi: CONSOLE_SCREEN_BUFFER_INFO = CONSOLE_SCREEN_BUFFER_INFO()
-
-  GetConsoleScreenBufferInfo(GetStdHandle(STD_OUTPUT_HANDLE), &csbi)
+  // If the function fails, the return value is zero.
+  // https://docs.microsoft.com/en-us/windows/console/getconsolescreenbufferinfo
+  let err = GetConsoleScreenBufferInfo(GetStdHandle(STD_OUTPUT_HANDLE), &csbi)
+  guard err != 0 else { return (80, 25) }
```
Comment (compnerd) [inline Sources/ArgumentParser/Usage/HelpGenerator.swift:359]: I would just fold this into a single statement:

```suggestion
guard GetConsoleScreenBufferInfo(GetStdHandle(STD_OUTPUT_HANDLE), &csbi) else {
  return (80, 25)
}
```

**Review by compnerd — COMMENTED** [review]
Thanks for looking into this!

**Comment by rauhul** [comment]
@swift-ci please test

**Comment by natecook1000** [comment]
Thanks, @rauhul! 🚢
