### PR TITLE
Fix zsh dashes in command names

### LINKED ISSUE #277: Dashes in command names break completion scripts
Dashes aren't valid variable identifier characters for Zsh (~and maybe Bash~ just Zsh). When building a completion script for a command that includes one or more dashes in the command name, the completion script prints errors instead of providing completions.

**ArgumentParser version:** `main` branch
**Swift version:** Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)

### Checklist
- [x] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce
Create a CLI tool with a dash in the command name, then generate and install a Zsh completion script for the command.

Command:
```swift
struct ExampleCommand: ParsableCommand {
  @Option var name: String
  @Flag var verbose = false
}
```

Script:
```
#compdef example-command
local context state state_descr line
_example-command_commandname=$words[1]
typeset -A opt_args

_example-command() {
    integer ret=1
    local -a args
    args+=(
        '--name:name:'
        '--verbose'
        '(-h --help)'{-h,--help}'[Print help information.]'
    )
    _arguments -w -s -S $args[@] && ret=0

    return ret
}


_custom_completion() {
    local completions=("${(@f)$($*)}")
    _describe '' completions
}

_example-command
```

### Expected behavior
Typing `example-command` and then `TAB` should offer completions.

### Actual behavior
The shell prints `_example-command:3: command not found: _example-command_commandname=example-command`.

### PR DESCRIPTION
**Pull request by adellibovi**
Hi, this PR fixes #277

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

### CODE REVIEW

File: Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift [hunk 1]
```diff
@@ -12,12 +12,13 @@
 struct ZshCompletionsGenerator {
   /// Generates a Zsh completion script for the given command.
   static func generateCompletionScript(_ type: ParsableCommand.Type) -> String {
-    let initialFunctionName = [type].completionFunctionName()
+    let initialFunctionName = [type].completionFunctionName().zshEscapingCommandName()
+    let commandName = type._commandName.zshEscapingCommandName()
 
     return """
-    #compdef \(type._commandName)
+    #compdef \(commandName)
```
Comment (natecook1000) [inline Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift:19]: I don't think this part can change — IIUC the `#compdef` tells Zsh what command the completions are for, so they need to match the executable.

File: Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift [hunk 2]
```diff
@@ -12,12 +12,13 @@
...
     local context state state_descr line
-    _\(type._commandName)_commandname=$words[1]
+    _\(commandName)_commandname=$words[1]
```
Comment (natecook1000) [inline Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift:21]: As far as I understand it, this is the only part that needs to change, since dashes _are_ allowed in the function names, just not as a variable name. Can you still reproduce the issue if you only change this part here? As an extra benefit, this smaller change wouldn't cause problems for people who declare both `sub-command` and `sub_command` subcommands (which is a bad idea, but it will surely happen eventually).

**Review by natecook1000 — COMMENTED** [review]
Thanks for tackling this, @adellibovi! 👏 A couple notes below.

File: Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift (hunk 2 above)
Comment (adellibovi) [reply Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift:21]: You are right,  this is the only required changes. I made the change and tried locally :) Thanks for catching it @natecook1000. PR updated!

**Comment by natecook1000** [comment]
@swift-ci Please test

**Review by natecook1000 — APPROVED** [review]
LGTM!
