### PR TITLE
Propogate ExpressibleByArgument conformance

### LINKED ISSUE #340: Incorrect ArgumentDefinition.help.allValues
`ArgumentDefinition.help.allValues` is empty for a `String, CaseIterable, ExpressibleByArgument` enum.

**ArgumentParser version:**
```
main
```
**Swift version:**
```
Apple Swift version 5.3.1 (swiftlang-1205.0.16.11 clang-1205.0.19.6)
Target: x86_64-apple-darwin20.3.0
```

### Checklist
- [x] If possible, I've reproduced the issue using the `main` branch of this package
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce
Run the attached sample, observe assertion firing.

### Expected behavior
The contents of `opt.help.allValues` should be the same as `Fruit.allValueStrings`.

### Actual behavior
The contents of `opt.help.allValues` is empty.

### Sample Code
[repro.zip](https://github.com/apple/swift-argument-parser/files/6852622/repro.zip)

### PR DESCRIPTION
**Pull request by rauhul**
- Adds an overload of ArgumentDefinition.init with a generic constraint
  on ExpressibleByArgument that propogates the conformance to the
  construction of ArgumentDefinition.Help. This allows the
  allValueStrings of the type conforming to ExpressibleByArgument to
  become the allValues property of the help object.

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

Fixes #340

### CODE REVIEW

**Comment by natecook1000** [comment]
Thanks for this fix, @rauhul! I'd rather go the other way, and make sure the generic parameter is maintained from the property wrapper initializer through to the `ArgumentDefinition.init` call. This way we're throwing away the `ExpressibleByArgument` conformance only to look it up again.

**Comment by rauhul** [comment]
@natecook1000 refactored to propagate the constraint, take a look when you have a moment :)

File: Sources/ArgumentParser/Parsing/ArgumentSet.swift [hunk 1]
```diff
@@ -159,7 +159,16 @@ extension ArgumentSet {
...
   /// Create a unary / argument that parses using the given closure.
   init<A>(key: InputKey, kind: ArgumentDefinition.Kind, parsingStrategy: ParsingStrategy = .default, parser: @escaping (String) -> A?, parseType type: A.Type = A.self, default initial: A?, completion: CompletionKind) {
-    self.init(kind: kind, help: ArgumentDefinition.Help(key: key), completion: completion, parsingStrategy: parsingStrategy, update: .unary({ (origin, name, value, values) in
+    self.init(key: key, kind: kind, parsingStrategy: parsingStrategy, parser: parser, parseType: type, default: initial, completion: completion, help: ArgumentDefinition.Help(key: key))
+  }
+
+  /// Create a unary / argument that parses using the given closure.
+  init<A: ExpressibleByArgument>(key: InputKey, kind: ArgumentDefinition.Kind, parsingStrategy: ParsingStrategy = .default, parser: @escaping (String) -> A?, parseType type: A.Type = A.self, default initial: A?, completion: CompletionKind) {
+    self.init(key: key, kind: kind, parsingStrategy: parsingStrategy, parser: parser, parseType: type, default: initial, completion: completion, help: ArgumentDefinition.Help(type: A.self, key: key))
```
Comment (natecook1000) [inline Sources/ArgumentParser/Parsing/ArgumentSet.swift:167]: 👍🏻

**Review by natecook1000 — COMMENTED** [review]
Yah, this is it — thanks @rauhul!

**Comment by natecook1000** [comment]
@swift-ci Please test

File: Tests/ArgumentParserUnitTests/HelpGenerationTests.swift [hunk 2]
```diff
@@ -505,6 +505,49 @@ extension HelpGenerationTests {
         """
     )
   }
+
+  struct AllValues: ParsableCommand {
+    enum Manual: Decodable, ExpressibleByArgument {
```
Comment (natecook1000) [inline Tests/ArgumentParserUnitTests/HelpGenerationTests.swift:510]: Looks like this just needs to be a RawRepresentable enum.
```suggestion
    enum Manual: String, ExpressibleByArgument {
```

Comment (rauhul) [reply Tests/ArgumentParserUnitTests/HelpGenerationTests.swift:510]: Ah, this is intentionally not a String to test that manually implemented `allValueStrings` works

Comment (natecook1000) [reply Tests/ArgumentParserUnitTests/HelpGenerationTests.swift:510]: Int works too, then. It’s not getting Decodable conformance synthesis without the raw form. (I suppose you could also implement `init(from:)`)

Comment (rauhul) [reply Tests/ArgumentParserUnitTests/HelpGenerationTests.swift:510]: Ah I overlooked this since 5.5 synthesized the conformance locally (somehow)

**Comment by rauhul** [comment]
@swift-ci please test
