### PR TITLE
Beautify `NSError` cases when thrown 💄 

### LINKED ISSUE #270: NSErrors aren't printed nicely when caught
NSError instances thrown from Objective-C aren't handled nicely by `MessageInfo`.

Because protocol conformances don't apply over bridging, `let e as CustomNSError` in an exception handler does not match NSError instances, even if the NSError happens to be bridgeable to `CocoaError` (or another domain-specific error type) that does conform to CustomNSError.

Note: In Foundation as of 2020, `NSError` and `CFError` conform to none of `CustomNSError`, `LocalizedError`, or any other error protocol other than `Error` itself. To handle NSError instances, `MessageInfo.init` needs to explicitly add a `case let e as NSError` clause.

**ArgumentParser version:** `0.3.2`
**Swift version:** 5.4

### Checklist
- [X] If possible, I've reproduced the issue using the `main` branch of this package
- [X] I've searched for [existing GitHub issues](https://github.com/apple/swift-argument-parser/issues)

### Steps to Reproduce

```swift
import Foundation
import ArgumentParser

struct Command: ParsableCommand {
  func run() throws {
    let url = URL(fileURLWithPath: "/This file does not exist")
    try print(NSData(contentsOf: url, options: .mappedIfSafe))
  }
}

Command.main()
```

### Expected behavior

```
$ swift run test
Error: The file “This file does not exist” couldn’t be opened because there is no such file.
```

### Actual behavior

```
$ swift run test 
Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “This file does not exist” couldn’t be opened \
because there is no such file." UserInfo={NSFilePath=/This file does not exist, \
NSUnderlyingError=0x7fd669706a40 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

### PR DESCRIPTION
**Pull request by schlagelk**
Ensures the `NSError` case is handled in `MessageInfo` and attempts to resolve #270 

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

### CODE REVIEW

File: Sources/ArgumentParser/Usage/MessageInfo.swift [hunk 1]
```diff
@@ -110,6 +121,8 @@ enum MessageInfo {
         self = .other(message: error.localizedDescription, exitCode: Int32(error.errorCode))
       case let error as LocalizedError where error.errorDescription != nil:
         self = .other(message: error.errorDescription!, exitCode: EXIT_FAILURE)
+      case let error as NSError:
+        self = .other(message: error.localizedDescription, exitCode: Int32(error.code))
```
Comment (lorentey) [inline Sources/ArgumentParser/Usage/MessageInfo.swift:125]: Please do not use the error code as the exit code; see #269. For now, `EXIT_FAILURE` is the best option.

Comment (schlagelk) [reply Sources/ArgumentParser/Usage/MessageInfo.swift]: @lorentey roger that - done on 37fb5d99ecc3e7d0fa12937514616bd3389caa6e

**Review by lorentey — APPROVED** [review]
LGTM! 👍

**Review by natecook1000 — APPROVED** [review]
Looks great, @schlagelk — thanks for your contribution! 👏🏻👏🏻

**Comment by natecook1000** [comment]
@swift-ci Please test

File: Sources/ArgumentParser/Usage/MessageInfo.swift [hunk 2]
```diff
@@ -73,6 +73,17 @@ enum MessageInfo {
...
+      // Send NSError back through the CommandError path
+      self.init(
+        error: CommandError(
+          commandStack: [type.asCommand],
+          parserError: .userValidationError(e)
+        ),
+        type: type
+      )
+      return
+
```
Comment (natecook1000) [inline Sources/ArgumentParser/Usage/MessageInfo.swift:86]: It turns out this bit isn't necessary! The default case handles general errors just fine.

File: Sources/ArgumentParser/Usage/MessageInfo.swift [hunk 3]
```diff
@@ -110,6 +121,8 @@ enum MessageInfo {
         self = .other(message: error.localizedDescription, exitCode: Int32(error.errorCode))
       case let error as LocalizedError where error.errorDescription != nil:
         self = .other(message: error.errorDescription!, exitCode: EXIT_FAILURE)
+      case let error as NSError:
+        self = .other(message: error.localizedDescription, exitCode: EXIT_FAILURE)
       default:
         self = .other(message: String(describing: error), exitCode: EXIT_FAILURE)
```
Comment (natecook1000) [inline Sources/ArgumentParser/Usage/MessageInfo.swift:127]: Here we have a problem — on macOS, the `error as NSError` cast always succeeds, which means we lose the customization for non-`NSError` errors that conform to `CustomStringConvertible`. Since `NSError`, in turn, conforms to `CustomStringConvertible`, there's no way to distinguish them by casting alone.

This is an unfortunate but successful way of distinguishing actual `NSError` errors from plain Swift errors:
```suggestion
      default:
        if Swift.type(of: error) is NSError.Type, let error = error as? NSError {
          self = .other(message: error.localizedDescription, exitCode: EXIT_FAILURE)
        } else {
          self = .other(message: String(describing: error), exitCode: EXIT_FAILURE)
        }
```

**Review by natecook1000 — COMMENTED** [review]
Thanks so much for tackling this, @schlagelk! We need a bit of a different approach for identifying `NSError`s — notes below.

File: Sources/ArgumentParser/Usage/MessageInfo.swift (hunk 3 above)
Comment (schlagelk) [reply Sources/ArgumentParser/Usage/MessageInfo.swift]: @natecook1000 interesting, and as always thanks for the amazing insight!  I'm wondering if the conditional cast to `NSError` needs to happen here for any reason then, or if a13105c would suffice?

Comment (natecook1000) [reply Sources/ArgumentParser/Usage/MessageInfo.swift]: Does that compile? I don’t think `localizedDescription` will be available on `error` until the cast succeeds. Also note that this bridging behavior isn’t consistent between macOS and Linux!

**Comment by natecook1000** [comment]
@swift-ci Please test

File: Sources/ArgumentParser/Usage/MessageInfo.swift (hunk 3 above)
Comment (schlagelk) [reply Sources/ArgumentParser/Usage/MessageInfo.swift]: It does compile!  In fact Xcode gave me a warning about the cast always succeeding. I'm just making sure I didn't miss anything, but I'm happy to add it in if it's necessary.

Comment (natecook1000) [reply Sources/ArgumentParser/Usage/MessageInfo.swift]: TIL! Let’s run with it :shipit:
